version: "3.8"

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  seed:
    image: lucysteve/sparta-node-app:v1
    depends_on:
      - mongo
    environment:
      DB_HOST: mongodb://mongo:27017/posts
    command: node seeds/seed.js
    
  app:
    build: . # added this as Docker Compose does NOT use your local Dockerfile automatically unless you tell it to build.
    image: lucysteve/sparta-node-app:v1
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      DB_HOST: mongodb://mongo:27017/posts
    command: npm start

volumes:
  mongo-data: